#!/bin/bash

echo "Pre-commit validation"

STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "src/.*.(js|jsx)$")

COLOR_RED="\033[0;31m"
COLOR_YELLOW="\033[0;33m"
COLOR_RESET="\033[0m"

info() {
  echo -e $COLOR_YELLOW
  echo "$1"
  echo -e $COLOR_RESET
}

warning() {
  echo -e $COLOR_RED
  echo "$1"
  echo -e $COLOR_RESET
}

PASS=true

if [[ "$STAGED_JS_FILES" != "" ]]; then
  info "RUN: prettier"

  echo "$STAGED_JS_FILES" | xargs ./node_modules/.bin/prettier --write

  if [[ "$?" != 0 ]]; then
    warning "FAILED: prettier"
    PASS=false
  fi

  info "RUN: eslint"
  echo "$STAGED_JS_FILES" | xargs ./node_modules/.bin/eslint --fix

  if [[ "$?" != 0 ]]; then
    warning "FAILED: eslint"
    PASS=false
  fi

  # Add back prettified files to staged
  echo "$STAGED_JS_FILES" | xargs git add
fi

if ! $PASS; then
  warning "Pre-commit validation failed: Your commit contains files that failed to pass validation. Please fix errors and try again."
  exit 1
fi

echo "Pre-commit validation passed."
exit 0
